import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms & Conditions — WatchFilter",
  description: "Terms governing your use of WatchFilter.",
};

export default function TermsPage() {
  return (
    <div className="legal-page">
      <div className="legal-container">
        <Link href="/" className="legal-back">← Back to WatchFilter</Link>

        <header className="legal-header">
          <div className="legal-brand">⚡ WatchFilter</div>
          <h1 className="legal-title">Terms &amp; Conditions</h1>
          <p className="legal-date">Effective date: May 20, 2025</p>
        </header>

        <section className="legal-section">
          <p className="legal-lead">
            By using WatchFilter you agree to these Terms. Please read them carefully before
            submitting any content for analysis.
          </p>
        </section>

        <section className="legal-section">
          <h2>1. The Service</h2>
          <p>
            WatchFilter ("the Service") is an AI-powered video intelligence platform that
            processes publicly available YouTube transcripts to generate structured briefings,
            data-point extractions, and audio summaries. The Service is provided "as is" for
            informational and research purposes.
          </p>
        </section>

        <section className="legal-section">
          <h2>2. Permitted Use</h2>
          <p>You may use WatchFilter to:</p>
          <ul>
            <li>Analyze publicly available YouTube videos for personal or professional research.</li>
            <li>Generate and listen to audio briefings of video content.</li>
            <li>Export summaries for private use, note-taking, or internal team communication.</li>
          </ul>
          <p>You may <strong>not</strong> use WatchFilter to:</p>
          <ul>
            <li>Republish, sell, or commercially redistribute AI-generated analyses as original works without attribution.</li>
            <li>Systematically scrape, bulk-analyze, or automate requests to the Service in a manner that degrades availability for other users.</li>
            <li>Circumvent rate limits, access controls, or any security mechanisms of the Service.</li>
            <li>Submit content that violates YouTube's Terms of Service or any applicable law.</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>3. Intellectual Property</h2>
          <p>
            <strong>WatchFilter software and interface</strong> — All source code, design, branding,
            and proprietary prompt engineering comprising the WatchFilter platform are the
            exclusive intellectual property of WatchFilter.
            © {new Date().getFullYear()} WatchFilter. All rights reserved. Unauthorized
            reproduction, modification, or distribution is prohibited.
          </p>
          <p>
            <strong>Third-party content</strong> — YouTube videos, transcripts, and associated
            metadata remain the property of their respective creators and rights holders.
            WatchFilter does not claim ownership over any third-party content processed through
            the Service. AI-generated analyses are derivative works and do not confer any rights
            over the underlying source material.
          </p>
          <p>
            <strong>Your content</strong> — By submitting a URL you confirm you have the right to
            process that content and grant WatchFilter a limited license to do so on your behalf.
          </p>
        </section>

        <section className="legal-section">
          <h2>4. Accuracy Disclaimer</h2>
          <p>
            WatchFilter analyses are generated by AI and are provided for informational purposes
            only. They are not financial, legal, or professional advice. Clickbait scores,
            credibility checks, and strategic-intent assessments reflect the AI model's
            interpretation of publicly available content — not verified fact-checking by humans.
            Always consult primary sources before acting on any information.
          </p>
        </section>

        <section className="legal-section">
          <h2>5. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, WatchFilter and its operators shall not be
            liable for any indirect, incidental, special, consequential, or punitive damages
            arising from your use of or inability to use the Service, including but not limited to
            loss of profits, data, or business opportunities.
          </p>
        </section>

        <section className="legal-section">
          <h2>6. Service Availability</h2>
          <p>
            We do not guarantee uninterrupted or error-free availability of the Service.
            We reserve the right to modify, suspend, or discontinue any feature at any time
            without notice.
          </p>
        </section>

        <section className="legal-section">
          <h2>7. Third-Party Terms</h2>
          <p>
            Use of WatchFilter is subject to the terms of third-party providers whose services
            power the platform, including{" "}
            <a href="https://openai.com/policies/usage-policies" target="_blank" rel="noopener noreferrer">OpenAI's Usage Policies</a>,{" "}
            <a href="https://www.youtube.com/t/terms" target="_blank" rel="noopener noreferrer">YouTube's Terms of Service</a>, and{" "}
            <a href="https://vercel.com/legal/terms" target="_blank" rel="noopener noreferrer">Vercel's Terms of Service</a>.
            You are responsible for ensuring your use complies with all applicable third-party terms.
          </p>
        </section>

        <section className="legal-section">
          <h2>8. Changes to These Terms</h2>
          <p>
            We may revise these Terms at any time. Continued use of the Service after changes
            are posted constitutes acceptance of the revised Terms.
          </p>
        </section>

        <section className="legal-section">
          <h2>9. Governing Law</h2>
          <p>
            These Terms are governed by applicable law. Any disputes shall be resolved through
            good-faith negotiation before any formal proceeding.
          </p>
        </section>

        <section className="legal-section">
          <h2>10. Contact</h2>
          <p>
            Questions about these Terms? Email us at{" "}
            <a href="mailto:hello@watchfilter.app">hello@watchfilter.app</a>.
          </p>
        </section>

        <footer className="legal-footer">
          <p>© {new Date().getFullYear()} WatchFilter. All rights reserved.</p>
          <div className="legal-footer-links">
            <Link href="/privacy">Privacy Policy</Link>
            <Link href="/terms">Terms &amp; Conditions</Link>
            <Link href="/">Back to App</Link>
          </div>
        </footer>
      </div>
    </div>
  );
}
